language: python
cache:
  pip: true
addons:
  postgresql: 9.6
  apt:
    packages:
     - postgresql-9.6-postgis-2.3

install: pip install tox python-coveralls
script: tox

matrix:
  include:
    - { python: 3.7, env: TOXENV=py37-2.1 }
    - { python: 3.7, env: TOXENV=docs }
    - { python: 3.7, env: TOXENV=flake8 }

    # https://github.com/travis-ci/travis-ci/issues/9815
    sudo: yes

  # we allow failures for now:
  allow_failures:
      - env: TOXENV=py37-2.1

after_success:
    coveralls
